# Generated by Django 5.0.6 on 2026-06-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_moveorder_cancel_reason_moveorder_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveorder',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
    ]
