# Generated by Django 5.2.1 on 2026-06-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressevent',
            name='stage',
            field=models.CharField(choices=[('created', '已预约'), ('claimed', '已抢单'), ('assigned', '已派单'), ('departed', '已出发'), ('loading', '装车中'), ('in_transit', '运输中'), ('unloading', '卸货中'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=20),
        ),
    ]
